include bindings/media.conf
include bindings/tiling.conf
include bindings/utilities.conf

# Application bindings
bindsym Super+Return exec foot
bindsym Super+Alt+Return exec foot sh -c toolbox enter
bindsym Super+Shift+Return exec brave-browser
bindsym Super+Shift+f exec thunar
bindsym Super+Alt+Shift+f exec thunar
bindsym Super+Shift+b exec brave-browser
bindsym Super+Shift+Alt+b exec brave-browser --incognito
bindsym Super+Shift+m exec spotify
bindsym Super+Shift+n exec nvim
bindsym Super+Shift+g exec whatsapp
bindsym Super+Shift+o exec obsidian
bindsym Super+Shift+slash exec bitwarden
