set $mod Super
default_orientation auto
seat seat0 hide_cursor 5000
smart_borders no_gaps
# default_border pixel 4
focus_on_window_activation urgent
focus_follows_mouse no

## Status Bar (man 5 sway-bar):
# bar {
#     position top
#
#     # When the status_command prints a new line to stdout, swaybar updates.
#     status_command while date +'%Y-%m-%d %I:%M:%S %p'; do sleep 1; done
#
#     colors {
#         statusline #ffffff
#         background #323232
#         inactive_workspace #323232 #323232 #5c5c5c
#     }
# }

## Startup
# xwayland disable
# exec mako > /tmp/mako.log 2>&1
# exec gammastep -l -7.702020:110.602791
#exec megasync

#exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK
#exec dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK
#exec systemd-notify --ready

