set $gnome-schema org.gnome.desktop.interface

exec_always {
    gsettings set $gnome-schema gtk-theme "Yaru-blue-dark"
    gsettings set $gnome-schema icon-theme "Yaru-blue-dark"
    gsettings set $gnome-schema cursor-theme "Yaru"
    gsettings set $gnome-schema font-name "Google Sans 11"
    gsettings set $gnome-schema monospace-font-name "Google Sans Mono 11"
    gsettings set $gnome-schema color-scheme "prefer-dark"
}


# class                 border  backgr. text    indicator child_border
client.focused          #6fb8e3 #6fb8e3 #1b2d40 #f2fcff   #6fb8e3
client.focused_inactive #4A6B80 #4A6B80 #d6e2ee #8bc9eb   #4A6B80
client.unfocused        #1b2d40 #1b2d40 #86b7d8 #4A6B80   #1b2d40
client.urgent           #f2fcff #f2fcff #1b2d40 #f2fcff   #f2fcff
client.placeholder      #1b2d40 #1b2d40 #d6e2ee #1b2d40   #1b2d40

client.background       #1b2d40
