bar {
    colors {
        background #1b2d40
        statusline #d6e2ee
        separator  #4A6B80

        #                  border  backgr. text
        focused_workspace  #6fb8e3 #6fb8e3 #1b2d40
        active_workspace   #4A6B80 #4A6B80 #d6e2ee
        inactive_workspace #1b2d40 #1b2d40 #86b7d8
        urgent_workspace   #f2fcff #f2fcff #1b2d40
        binding_mode       #f2fcff #f2fcff #1b2d40
    }
}
