### System Dialogs & Generic Roles
# File Pickers
for_window [title="(?i)(?:Open|Save) (?:File|Folder|As)"] {
    floating enable
    resize set 800 600
}

# Common Window Roles & Types
for_window [window_role="(?i)(pop-up|bubble|task_dialog|Preferences)"] floating enable
for_window [window_type="dialog"] floating enable
for_window [window_type="menu"] floating enable

### Specific App Rules (Floating)
# System Utilities
for_window [instance="lxappearance"] floating enable
for_window [app_id="pamac-manager"] floating enable
for_window [app_id="xsensors"] floating enable
for_window [title="^wlay$"] floating enable

# Development & Specialized Tools
for_window [app_id="dragon-drop"] floating enable, sticky enable
for_window [app_id="floating_shell"] floating enable, border pixel 1, sticky enable
for_window [instance="around"] floating enable, sticky enable

# App-Specific Sub-windows
for_window [app_id="firefox" title="^Library$"] floating enable, border pixel 1, sticky enable
for_window [app_id="thunderbird" title=".*Reminder"] floating enable
