# Application bindings
bindsym Super+Return exec xdg-terminal-exec
bindsym Super+Alt+Return exec xdg-terminal-exec sh -c ssh oracle-dev
bindsym Super+Shift+Return exec brave-origin
bindsym Super+Shift+f exec nautilus
bindsym Super+Shift+b exec brave-origin
bindsym Super+Shift+Alt+b exec brave-origin --incognito
bindsym Super+Shift+m exec brave-origin --app-id=$YOUTUBE_MUSIC_APP_ID
bindsym Super+Shift+n exec nvim
bindsym Super+Shift+g exec brave-origin --app-id=$WHATSAPP_WEB_APP_ID
bindsym Super+Shift+o exec obsidian
bindsym Super+Shift+slash exec bitwarden
bindsym Super+Shift+z exec zed --new
