# bindsym --locked XF86KbdBrightnessUp exec
# bindsym --locked XF86KbdBrightnessDown exec
# bindsym --locked XF86KbdLightOnOff exec 

bindsym --locked XF86TouchpadToggle exec input type:touchpad events toggle enabled disabled
bindsym --locked XF86TouchpadOn exec input type:touchpad events enabled
bindsym --locked XF86TouchpadOff exec input type:touchpad events enabled

# bindsym XF86ScreenSaver exec $locking
# bindsym XF86Battery exec 
# bindsym XF86Sleep exec "$locking; sleep 1; pkill -USR1 swayidle"
# bindsym XF86WLAN exec airplane-mode
# bindsym XF86WebCam exec 
# bindsym XF86Display exec 
