bindsym Super+Shift+c reload

# Menus
bindsym Super+space exec walker
bindsym Super+Ctrl+e exec walker -m symbols
bindsym Super+Ctrl+c exec walker --provider menus:capture
bindsym Super+Ctrl+o exec walker --provider menus:toggle
bindsym Super+Ctrl+h exec walker --provider menus:hardware
bindsym Super+Alt+space exec walker --provider menus:start
bindsym Super+escape exec walker --provider menus:system
bindsym XF86PowerOff exec walker --provider menus:system
bindsym XF86Calculator exec walker -m calc
bindsym Super+Shift+e exec swaynag --type warning \
    --message '' \
    --dismiss-button 'Cancel' \
    --button 'Exit' 'swaymsg exit' \
    --button 'Sleep' 'systemctl suspend' \
    --button 'Hibernate' 'systemctl hibernate' \
    --button 'Reboot' 'systemctl reboot' \
    --button 'Poweroff' 'systemctl poweroff'

# Aesthetics
bindsym Super+Shift+space exec killall -SIGUSR1 waybar
bindsym Super+Shift+Ctrl+space exec killall -SIGUSR2 waybar

# Notifications
bindsym Super+comma exec makoctl dismiss
bindsym Super+Shift+comma exec makoctl dismiss --all
# bindsym Super+Ctrl+COMMA exec toggle-notification-silencing
bindsym Super+Alt+comma exec makoctl invoke
bindsym Super+Shift+Alt+comma exec makoctl restore

# Captures
# bindsym Print exec grim
# bindsym Shift+Print exec slurp | grim -g -
