bindsym Super+Shift+c reload

# Menus
bindsym Super+space exec rofi -show combi -combi-modes drun
bindsym XF86PowerOff exec systemctl poweroff
bindsym XF86Calculator exec gnome-calculator
bindsym $mod+Shift+e exec swaynag --type warning \
    --message '' \
    --dismiss-button 'Cancel' \
    --button 'Exit' 'swaymsg exit' \
    --button 'Sleep' 'systemctl suspend' \
    --button 'Hibernate' 'systemctl hibernate' \
    --button 'Reboot' 'systemctl reboot' \
    --button 'Poweroff' 'systemctl poweroff'

# Aesthetics
bindsym Super+Shift+space exec pgrep -x waybar && pkill -x waybar || waybar &>/dev/null &

# Notifications
bindsym Super+comma exec dunstctl close
bindsym Super+Shift+comma exec dunstctl close-all
# bindsym Super+Ctrl+COMMA exec toggle-notification-silencing
bindsym Super+Alt+comma exec dunstctl action
bindsym Super+Shift+Alt+comma exec dunstctl history-pop

# Captures
# bindsym Print exec grim
# bindsym Shift+Print exec slurp | grim -g -
