# https://codeberg.org/dnkl/foot/src/branch/master/foot.ini

login-shell=yes
font=Google Sans Code:size=13,Symbols Nerd Font Mono:size=13,monospace:size=13

[cursor]
style=beam

[main]
include=/usr/share/foot/themes/solarized-dark
